import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/navbar'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <NavBar/>
      <div className="bg-white py-5 px-10 md:px-20">
        <h3 className="text-2xl font-bold">TERMS AND CONDITIONS</h3>
        <p>
        Effective Date: May 01st 2023<br/>  
These Terms and Conditions constitute a legally binding agreement made between you, whether personally or on behalf of an entity Kirikeni Okwein, concerning your access to and use of the platform.<br/>
In order to help make the Site a secure environment for us to provide the Services, all users are required to accept and comply with these Terms and Conditions, including the Services Agreement posted on the Site, which is incorporated into these Terms and Conditions. You agree that by accessing the Site and/or the Services, you have read, understood, and agree to be bound by all of these Terms and Conditions. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS AND CONDITIONS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND/OR THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.<br/>
Supplemental Terms and Conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms and Conditions at any time and for any reason. We will alert you about any changes by updating the "Last updated" date of these Terms and Conditions, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Terms and Conditions to stay informed of updates. You will be subject to and will be deemed to have been made aware of and to have accepted, the changes in any revised Terms and Conditions by your continued use of the Site after the date such revised Terms and Conditions are posted.<br/>
The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.<br/>
Intellectual Property Rights<br/>
Unless otherwise indicated, the Site and the Services are our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the "Content") and the trademarks, service marks, and logos contained therein (the “Marks”) are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws of the United States, foreign jurisdictions, and international conventions.<br/>
The Content and the Marks are provided on the Site “AS IS” for your information and personal use only. We make no representation that the Site is appropriate or available outside the United States. Access of the Site from outside the United States is done at your own initiation and you are responsible for compliance with applicable laws.<br/>
You may print or have printed by any third party any downloadable material contained on the Site provided that: (1) the material is solely for non-commercial and personal use; (2) no copyright, author attribution, trademark, legend, or other proprietary notice is removed from the material; and (3) the material is not altered in any manner. Except as expressly provided in these Terms and Conditions, no part of the Site or the Services and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.<br/>
Provided that you are eligible to use the Site, you are granted a limited license to access and use the Site and to download or print a copy of any portion of the Content to which you have properly gained access solely for your personal, non-commercial use. You expressly acknowledge and agree that we transfer no ownership or intellectual property interest or title in and to the Sit or its content to you or anyone else. We reserve all rights not expressly granted to you in and to the Site, the Content, and the Marks.<br/>
        </p>
        <h3 className="text-2xl font-bold pt-4">User Representations and Responsibilities</h3>
        <p>Self-Managed Account<br/>
To register and open an account with us, you may be asked to provide certain information including personal information. By opening an account or using this Site, you understand that your account is managed by yourself, thus you are responsible for any and all orders placed with your account and that all orders entered by you or on your behalf are unsolicited and based on your own investment decisions or the investment decision of your duly authorized representative or agent. <br/>Accordingly, you acknowledge that neither us nor any of our employees, agents, principals, or representatives:
</p>
<ol className='list-decimal'>
  <li>provide investment advice in connection with this account;</li>
  <li>recommend any security, transaction or order;</li>
  <li>solicit orders;</li>
  <li>act as a market maker in any security;</li>
  <li>make discretionary trades; and</li>
  <li>make discretionary trades; and
produce or provide any first-party research that provides specific investment strategies such as buy, sell or hold recommendations, first-party ratings and/or price targets. To the extent research materials or similar information are available through the Site, you understand that these materials are only intended for informational and educational purposes, and they do not constitute any recommendation to enter any securities transactions or to engage in any investment strategies.</li>
</ol>

<h3 className="text-2xl font-bold pt-4">User Registration</h3>
<p>You may be required to register with the Site in order to access the Services. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.</p>
     
     
<h3 className="text-2xl font-bold pt-4">User Data</h3>
<p>The Service may permit you and other Users to submit, post, transmit and share content with other users, which may include, without limitation, personal and representative profiles and information sheets on certain private companies or other issuers, streaming feeds articles, documents, brochures, presentations, pictures, images, audiovisual works, other information materials and any user comments or other unedited or third party content submitted by you and other Users on or through the Services (collectively, "User Content"). User Content excludes personal information, such as your name, e-mail address, physical address, phone number(s), and credit card information that you may provide to us. With respect to such User Content submitted by you or any other Users of the Site or Service, you represent, warrant and affirm as follows:
</p>
<ul className='list-disc'>
  <li>User Content is made available on or through the Service for informational purposes only and is not otherwise controlled by Ark7. You understand that Ark7 does not guarantee any accuracy or confidentiality with respect to any such User Content, and strongly recommends that you think carefully about what you transmit, submit or post to or through the Service.</li>
  <li>User Content you submit to the Service or Ark7’ or any Ark7 licensee’s use of such User Content pursuant to these Terms, will not: (i) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (ii) violate any applicable laws, rules or regulations (including, without limitation, United States federal and state securities or blue sky laws or regulations, securities exchange or self-regulatory organization’s rules or regulations, or equivalent laws or regulations in foreign jurisdictions); (iii) intentionally interfere with the operation of the Site, without limitation, mail or "post" bombing, news bombing, other flooding techniques, deliberate attempts to overload a system and broadcast attacks, or attempts to avoid messaging blocking; or (iv) require obtaining a license from or paying any fees and/or royalties by Ark7 to any third party for the performance of any services you have chosen to be performed by Ark7 or for the exercise of any rights granted in these Terms, unless you and Ark7 otherwise agree.</li>
  <li>All User Content and any information contained in such User Content are the sole responsibility of the person(s) who originated such User Content. This means that you, and not Ark7, are entirely responsible for all User Content that you upload, post, transmit, or otherwise make available through the Service as well as any consequences of submitting and publishing your User Content on the Service. You affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to publish User Content you submit; and you license to Ark7 all patent, trademark, trade secret, copyright or other proprietary rights in and to such User Content for publication on the Service pursuant to these Terms and Conditions.</li>
  <li>By submitting User Content to Ark7, you hereby grant Ark7 and its affiliates, sublicensees, partners, designees, and assignees a worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the User Content in connection with the Service and Ark7' (and its successors' and affiliates') business, including without limitation for promotion and redistribution of part or all of the Service (and derivative works thereof) in any media formats and through any media channels.</li>
  <li>You hereby grant each User of the Service a non-exclusive license to access your User Content through the Service, and to use, reproduce, distribute, display and perform such Content as permitted through the functionality of the Service and under these Terms and Conditions. The above licenses granted by you in User Content you submit to the Service terminate within a commercially reasonable time after you remove or delete your User Content from the Service. You understand and agree, however, that Ark7 may retain, but not display, distribute, or perform, server copies of your User Content that has been removed or deleted.</li>
  <li>Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Services. You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.</li>
  <li>You may be exposed to User Content that is, without limitation, inaccurate, inappropriate, misleading, unlawful, offensive or otherwise objectionable and Ark7 makes no representations or warranties regarding any User Content, is not responsible for the accuracy, usefulness, or intellectual property rights of or relating to any User Content and does not endorse any User Content submitted to the Service by any user or other licensor, as well as any opinion, recommendation, or advice expressed therein and all such content is offered "AS IS" and "AS AVAILABLE".</li>

</ul>
<h3 className="text-2xl font-bold pt-4">Mobile Application License</h3>
<h3 className="text-1xl font-bold pt-4">Use License</h3>
<p>if you access the Services via a mobile application, then we grant you a revocable, non-exclusive, non-transferable, limited right to install and use the mobile application on wireless electronic devices owned or controlled by you, and to access and use the mobile application on such devices strictly in accordance with the Terms and Conditions of this mobile application license contained in these Terms and Conditions. You may print and download such information from the Site solely for your personal use, provided that all hard copies contain all copyright and other such notices contained in such information. You shall not: (1) decompile, reverse engineer, disassemble, attempt to derive the source code of, or decrypt the application; (2) make any modification, adaptation, improvement, enhancement, translation, or derivative work from the application; (3) violate any applicable laws, rules, or regulations in connection with your access or use of the application; (4) remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) posted by us or the licensors of the application; (5) use the application for any revenue generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended; (6) make the application available over a network or other environment permitting access or use by multiple devices or users at the same time; (7) use the application for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for the application; (8) use the application to send automated queries to any website or to send any unsolicited commercial e-mail; or (9) use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, licensing, or distribution of any applications, accessories, or devices for use with the application.</p>
<h3 className="text-2xl font-bold pt-4">Mobile Application License</h3>
<p>The following terms apply when you use a mobile application obtained from either the Apple Store or Google Play (each an "App Distributor") to access the Services: (1) the license granted to you for our mobile application is limited to a non-transferable license to use the application on a device that utilizes the Apple iOS or Android operating systems, as applicable, and in accordance with the usage rules set forth in the applicable App Distributor’s Terms and Conditions; (2) we are responsible for providing any maintenance and support services with respect to the mobile application as specified in the Terms and Conditions of this mobile application license contained in these Terms and Conditions or as otherwise required under applicable law, and you acknowledge that each App Distributor has no obligation whatsoever to furnish any maintenance and support services with respect to the mobile application; (3) in the event of any failure of the mobile application to conform to any applicable warranty, you may notify the applicable App Distributor, and the App Distributor, in accordance with its terms and policies, may refund the purchase price, if any, paid for the mobile application, and to the maximum extent permitted by applicable law, the App Distributor will have no other warranty obligation whatsoever with respect to the mobile application; (4) you represent and warrant that (i) you are not located in a country that is subject to a U.S. government embargo, or that has been designated by the U.S. government as a “terrorist supporting” country and (ii) you are not listed on any U.S. government list of prohibited or restricted parties; (5) you must comply with applicable third-party terms of agreement when using the mobile application, e.g., if you have a VoIP application, then you must not be in violation of their wireless data service agreement when using the mobile application; and (6) you acknowledge and agree that the App Distributors are third-party beneficiaries of the Terms and Conditions in this mobile application license contained in these Terms and Conditions, and that each App Distributor will have the right (and will be deemed to have accepted the right) to enforce the Terms and Conditions in this mobile application license contained in these Terms and Conditions against you as a third-party beneficiary thereof.</p>
<h3 className="text-2xl font-bold pt-4">Mobile Application License</h3>
<p>These Terms and Conditions and any policies or operating rules posted by us on the Site or in respect to the Services constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Terms and Conditions shall not operate as a waiver of such right or provision. These Terms and Conditions operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these Terms and Conditions is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms and Conditions and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Terms and Conditions. You agree that these Terms and Conditions will not be construed against us by virtue of having drafted them. You hereby waive any and all defenses you may have based on the electronic form of these Terms and Conditions and the lack of signing by the parties hereto to execute these Terms and Conditions.</p>
      </div>
      <Footer/>
    </>
  )
}
